### ISSUE TITLE
Company Logo - Testing scenario for duplicates

### ISSUE THREAD

**Issue by rtemery** [icrunchdata/development#102]
Testing - what happens on the second post IF company logo was uploaded on the first post?

**Comment by rtemery** [comment]
So far it seems a duplicate is accepted. I'll report it.

**Comment by rtemery** [comment]
Let's re-test this on a manual posting to see if a duplicate is created. I'm fairly sure it is a bug that will tell us for sure.

**Comment by annabhill** [comment]
Need to report bug.

**Comment by rtemery** [comment]
Didn't we determine this was (not) an issue afterall, and that the image isn't uploaded in duplicate?

**Comment by annabhill** [comment]
Yes, as far as we can tell. Closing for now.
