### ISSUE TITLE
Social Share Migration

### ISSUE THREAD

**Issue by rtemery** [icrunchdata/development#110]
Apply code for social share migration

**Comment by annabhill** [comment]
Revisit Settings > Tweet Counts

**Comment by rtemery** [comment]
Implemented - propagating now.

**Comment by annabhill** [comment]
Also: Fix floating social share to float under the site footer menu. Currently displays over it.

**Comment by rtemery** [comment]
Made a code change. Let's wait 24 hours to see if the APIs update.

**Comment by rtemery** [comment]
Waiting on support

**Comment by rtemery** [comment]
Implemented on News domain to see if that works.  Soaking now.

**Comment by rtemery** [comment]
Not sure what to do on this -- closing for now.
