### ISSUE TITLE
Create ad units

### ISSUE THREAD

**Issue by annabhill** [icrunchdata/development#112]
Leaderboard on homepage
Leaderboard on /find-jobs
Build out all other medium rectangle zones

**Comment by rtemery** [comment]
Ad units created - awaiting activation

**Comment by rtemery** [comment]
Active and ready:

- [ ] Billboard needs alignment center
- [ ] Leaderboard needs mobile responsive css

**Comment by rtemery** [comment]
Gonna wait on this one. If we decide to abandon display, this will be unnecessary work. I'd rather focus on investing dev time on content related things unless we have a special request from a _paying_ client.

**Comment by rtemery** [comment]
Done -- can create new tickets on this if needed.
