### ISSUE TITLE
Editorial Team page

### ISSUE THREAD

**Issue by annabhill** [icrunchdata/development#119]
Create page /editorial-team/
Create custom sidebar
'Become a contributor' copy and button
Go-live with gallery
Settings
Add link from footer (Replace 'Read the Latest')

**Comment by rtemery** [comment]
Done so far:
-Page created
-Sidebar created
-Become a Contributor link

Left to do:
-Contributor gallery
-Settings
-Footer menu change

**Comment by rtemery** [comment]
More done:
-Footer menu is live

Left to do:
-Contributor gallery (go-live)
-Compare settings are consistent
