### ISSUE TITLE
XML Feed

### ISSUE THREAD

**Issue by rtemery** [icrunchdata/development#166]
XML Feed support for Post method.

**Comment by rtemery** [comment]
Initial research on this now.

**Comment by rtemery** [comment]
Insertion order field was added.

**Comment by rtemery** [comment]
Left to do:
- [ ] update xml document

**Comment by rtemery** [comment]
Research HTTP Post method.

**Comment by annabhill** [comment]
Agency test successful. Need to update documentation.

**Comment by rtemery** [comment]
Documentation updated

**Comment by rtemery** [comment]
Waiting on re-test.

**Comment by annabhill** [comment]
Re-test successful. Ready to go-live. Complete!
