### ISSUE TITLE
Company Logo and Resume Upload - Styling

### ISSUE THREAD

**Issue by annabhill** [icrunchdata/development#172]
On the /post-a-job page: In Company Logo field, need to style the 'Choose File' button and font size/spacing for text that reads 'No file chosen'. 

- Same styling goes for the Resume/CV Upload field when applying for a job via email.

**Comment by rtemery** [comment]
Bold is removed.

Ticket opened on the button and subtext issue -- maybe just remove the subtext since it doesn't add much value?

**Comment by rtemery** [comment]
Moving second item to it's own ticket.
