### ISSUE TITLE
Employer Dash - Change Intro Text

### ISSUE THREAD

**Issue by rtemery** [icrunchdata/development#173]
Change intro text on employer dash. Can you detail the path where I can revise this text?

**Comment by annabhill** [comment]
Admin > Tools > Text Changes

**Comment by rtemery** [comment]
Thanks, can you paste the text here for me?

**Comment by annabhill** [comment]
/employer-account/
Hello %s%s%s, welcome to the new employer experience! Find your options in the top menu labeled FOR EMPLOYERS.

/manage-jobs/
Your jobs are shown below. Please note that application stats cannot be tracked for third-party ATS routing. Applications are tracked for email routing only.

**Comment by rtemery** [comment]
Done
