### ISSUE TITLE
Conversion Tracking Code

### ISSUE THREAD

**Issue by annabhill** [icrunchdata/development#208]
- Need to add conversion tracking code to the _checkout confirmation page_ that comes after this form is filled out: https://icrunchdata.com/checkout/

- See code attached. This code need to be placed only on the confirmation page in order for it to work correctly. This code should be placed above the </body> tag on that page.

[google-adwords-conversion-tracking.txt](https://github.com/icrunchdata/development/files/715332/google-adwords-conversion-tracking.txt)

**Comment by rtemery** [comment]
Read through this email, here's my response:

I'm already familiar with how this works. Please tell him we have Google Universal Analytics (and not Google Legacy Analytics), therefore the tracking code is not necessary to paste (unless this is Go-North tracking proprietary code).

As far as the shopping cart values - we don't have plans to implement that at this time. 98% of our online transactions are $375. So this value is pre-set in our goal tracking in Google Universal Analytics.

**Comment by rtemery** [comment]
This is ready for testing in Staging.

**Comment by rtemery** [comment]
In production -- done.
