### ISSUE TITLE
PPC Ecommerce Tracking Configuration

### ISSUE THREAD

**Issue by annabhill** [icrunchdata/development#210]
- The two steps for Google AdWords and Bing will track the conversion count, but they do not track revenue by default. In order to track revenue, custom code must be added on the checkout confirmation page that will populate each tracking script with revenue data.

- SN cannot tell us exactly how to implement it on the site (as each site is very different); SN can only provide instructions from Google and Bing on how to set it up. See below.

[ppc-ecommerce-tracking-configuration-instructions.docx](https://github.com/icrunchdata/development/files/715343/ppc-ecommerce-tracking-configuration-instructions.docx)

**Comment by rtemery** [comment]
This makes no sense -- closed.
