### ISSUE TITLE
Password Strength Solution

### ISSUE THREAD

**Issue by rtemery** [icrunchdata/development#214]
I have a solution test the password restrictions.

**Comment by rtemery** [comment]
No complaints so far. Closed for now.

**Comment by rtemery** [comment]
I've pushed an update to this. Password meter is still displayed, however you can still register with normal passwords now. Tested okay for me in staging. Can you test in production please?

**Comment by rtemery** [comment]
Testing scenarios needed:
1. Register as Employer
2. Post a job with automatic registration.
3. Login to existing account (just make sure nothing was broken).

**Comment by annabhill** [comment]
3 scenarios tested successfully.

**Comment by rtemery** [comment]
Awesome! 👍
