### ISSUE TITLE
Job alerts modal popup

### ISSUE THREAD

**Issue by rtemery** [icrunchdata/development#22]
Find Jobs: Add popup for job alert signup /Jobs/. Pending with issue, waiting on response. Need to find an html solution that doesn't break this.

**Comment by rtemery** [comment]
Pro tip from Erica: Regarding styling elements inside an iFrame, you have to add the CSS directly to the page being loaded by iFrame. So if you're adding an iFrame like:

<iframe src="http://www.mysite.com/my-epic-optin.html"></iframe>

You would add the CSS to the "my-epic-optin.html" file.

**Comment by annabhill** [comment]
added custom css to adserving platform.  Needs testing in mobile after go-live
