### ISSUE TITLE
Cart page optimization

### ISSUE THREAD

**Issue by rtemery** [icrunchdata/development#44]
Currently there is no way to remove a product from checkout due to the /cart/ page being omitted from the funnel.  Needs addressing.

**Comment by annabhill** [comment]
Consider adding /cart and cart menu icon so user can remove cart items if needed. Kill links to product pages, however. And add back checkout button.

**Comment by rtemery** [comment]
Add code for 'continue shopping' redirect to /checkout/

**Comment by rtemery** [comment]
redirect link has been changed

**Comment by rtemery** [comment]
Cart menu icon and prepend placement- Done.
