### ISSUE TITLE
Mobile Styling Issues - Round 1

### ISSUE THREAD

**Issue by rtemery** [icrunchdata/development#52]
1a - Job listing body text isn't mobile responsive.  Might need a max-width setting for media queries.  And/or support.

**Comment by rtemery** [comment]
This is due to the width setting in functions php and child css.  See original theme dimensions.

**Comment by annabhill** [comment]
Logo isn't resizing for mobile. Menu crowded

**Comment by annabhill** [comment]
3 - Issue with hero background image repeating.
