### ISSUE TITLE
Terms and Conditions

### ISSUE THREAD

**Issue by rtemery** [icrunchdata/development#57]
Reminder to format content and break out the Job Advertising Guidelines to it's own page.

**Comment by rtemery** [comment]
Done - Needs to be editorialized:

/terms/  (section 14 to end of doc)
/advertising-media-guidelines/
/job-advertising-guidelines/

- might need links back to /terms/ from these pages.  

(help :)

**Comment by annabhill** [comment]
Done - Review first sentence on /job-advertising-guidelines/ and approve.
