### ISSUE TITLE
Resume Upload Issue - Filename not displayed

### ISSUE THREAD

**Issue by annabhill** [icrunchdata/development#64]
Apply Now > Resume/CV Upload > 
The file input field/label (i.e. 'No file chosen') does not display. Candidate needs visual cue that his file is uploaded. Is the visibility on this hidden?

**Comment by rtemery** [comment]
Also, required validation not working

**Comment by rtemery** [comment]
Support acknowledged this.  Waiting on resolution.

**Comment by rtemery** [comment]
Done - tested OK
