### ISSUE TITLE
Replace featured jobs - News Site

### ISSUE THREAD

**Issue by rtemery** [icrunchdata/development#81]
We need to replace the featured jobs widget on news site.

**Comment by annabhill** [comment]
See Embeddable Job Widget documentation:
https://wpjobmanager.com/document/embeddable-job-widget/

**Comment by rtemery** [comment]
Done - Good find on that. Double check placement and styling.  Close when you're ready.

**Comment by annabhill** [comment]
Add 3 or 4 more stories in the homepage news feed for visual balance.
Otherwise, looks great.

**Comment by rtemery** [comment]
Done.
