### ISSUE TITLE
Permalinks - change order

### ISSUE THREAD

**Issue by rtemery** [icrunchdata/development#87]
This would be a nice enhancement to change the order of the /jobs/ permalinks to be:

/jobs/job-title-first/location-second/

**Comment by rtemery** [comment]
Waiting on support for this

**Comment by rtemery** [comment]
I have a solution for this in Staging environment. Should now be: job-title-location

Needs testing before I can push to production.

**Comment by annabhill** [comment]
Test successful. Push to production.

**Comment by rtemery** [comment]
In production - done.
